apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfc-database-chart.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "rfc-database-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rfc-database-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rfc-database-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: database
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
              protocol: TCP
          volumeMounts:
            - name: database-volume
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ .Values.postgres.user }}"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ .Values.postgres.user }}"
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: {{ include "rfc-database-chart.fullname" . }}-database-pvc
