CREATE OR REPLACE FUNCTION refresh_daily_percentiles()
RETURNS TRIGGER AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY ASP.sw_percentiles;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER;